server {
    listen 80;

    # Раздача статики сайта
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Проксирование запросов к API Авторизации
    location /api/auth/ {
        proxy_pass http://auth-service:8000/;
    }

    # Проксирование запросов к API Профиля
    location /api/profile/ {
        proxy_pass http://profile-service:8000/;
    }
}
